vich_uploader:
    db_driver: orm

    mappings:
        sponsor:
            uri_prefix: /images/sponsors
            upload_destination: '%kernel.project_dir%/public/assets/images/sponsors'
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        news:
            uri_prefix: /images/uploads
            upload_destination: '%kernel.project_dir%/public/assets/images/uploads'
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
