easy_admin:
  entities:
      User:
        class: App\Entity\User
        label: 'Utilisateurs'
        edit:
          title: 'Créer/Éditer un utilisateur'
#          fields:
 #           - {property: 'UserName', label: 'Pseudo', type: 'text'}
  #          - {property: 'NomUser', label: 'Nom', type: 'text'}
   #         - {property: 'PrenomUser', label: 'Prénom', type: 'text'}
    #        - {property: 'EmailUser', label: 'Email', type: 'email'}
     #       - {property: 'TelephoneUser', label: 'Telephone', type: 'text'}
      #      - {property: 'AdresseUser', label: 'Adresse', type: 'text'}
       #     - {property: 'IdVille', label: 'Ville', type: 'choice'}

        list:
          title: 'Utilisateurs'
          fields:
            - {property: 'Isvalide', label: 'Actif/Banni', type: 'toggle'}
            - {property: 'UserName', label: 'Pseudo'}
            - {property: 'NomUser', label: 'Nom'}
            - {property: 'PrenomUser', label: 'Prénom'}
            - {property: 'EmailUser', label: 'Email'}
            - {property: 'TelephoneUser', label: 'Telephone'}
            - {property: 'AdresseUser', label: 'Adresse'}
            - {property: 'dateInscription', label: 'Date', format: 'd/m/Y à H:i:s'}